var five = 5;
var ten = 10;
console.log("i have written an arithmatic operation.its result should be true.");
console.log("test 1: five is equal to 5?");
console.log(five == 5);
console.log("\ni am writing a conditional test below and its answer should be true.");
console.log("test 2: ten is equal to 10?");
console.log(ten == 10);
console.log("\ni am writing a conditional test and its result should be true.");
console.log("test 3: 5 is not equal to 10");
console.log(five != ten);
console.log("\ni am writing a conditional test and its result should be true.");
console.log("test 4: 10 is greater than 5");
console.log(ten > 5);
console.log("\ni am writing a conditional test and its result should be true.");
console.log("test 5: 5 is smaller than10");
console.log(five < ten);
console.log("\ni am writing a conditional test and its result should be false.");
console.log("test 6: 10 is smaller than 5");
console.log(ten < 5);
console.log("\ni am writing a conditional test and its result should be false.");
console.log("test 7: 5 is equql to 10");
console.log(five == ten);
console.log("\ni am writing a conditional test and its result should be false.");
console.log("test 8: 10 is not equal to 10");
console.log(ten != ten);
console.log("\ni am writing a conditional test and its result should be false.");
console.log("test 9: 5 is greater than 10");
console.log(five > ten);
console.log("\ni am writing a conditional test and its result should be false.");
console.log("test 10: 10 is smaller than 5");
console.log(ten < five);
